[package]
name = "lpx_mode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = { path = "../../../midir" }
midi_connection = { path = "../midi_connection" }
